# Generated by Django 4.1.2 on 2023-01-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, default=69, max_digits=12),
            preserve_default=False,
        ),
    ]
