# Generated by Django 4.1.2 on 2023-01-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkania', '0002_apartment_url_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='Apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='mieszkania.apartment'),
        ),
    ]
