# Generated by Django 4.1.2 on 2023-01-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkania', '0003_price_timestamp_alter_price_apartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='Apartment',
            new_name='apartment',
        ),
    ]
