# Generated by Django 4.1.2 on 2023-01-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkania', '0004_rename_apartment_price_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
